addons:
  apt:
    packages:
      - rsync
      - sshpass
before_script:
  - npm install gulp
sudo: true
dist: trusty
node_js: "stable"
install: npm install
branches:
  only:
    - master
script: gulp compile
after_success:
  - test $TRAVIS_BRANCH = "master" && rsync -chavzP --rsh="sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no -l $SSH_USERNAME" build/* $SSH_USERNAME@ituk.ee:/var/liitu/build